version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: book-db-postgres
    ports: ['5432:5432']
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
